# 1.Menyambungkan Google Drive

Google Drive digunakan sebagai tempat penyimpanan dataset sehingga file Excel dapat dibaca langsung oleh Google Colab.

In [5]:
from google.colab import drive
import os

# Cek apakah folder mount sudah ada
if not os.path.exists('/content/drive/MyDrive'):
    drive.mount('/content/drive')
    print("Google Drive berhasil di-mount.")
else:
    print("Google Drive sudah terhubung.")

Google Drive sudah terhubung.

# 2.Import Library

Library yang digunakan untuk proses data cleansing, terutama pandas untuk membaca dan mengolah data Excel, serta numpy untuk operasi numerik.

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings('ignore')

print("Library berhasil di-import.")

Library berhasil di-import.

# 3.Menentukan Lokasi File

Menentukan lokasi dataset yang sudah disimpan di Google Drive.

In [7]:
file_path = '/content/drive/MyDrive/Colab Notebooks/DataCleansingCallCenter/Call-Center-Data-Messy.xlsx'

print("Lokasi file:")
print(file_path)

Lokasi file:
/content/drive/MyDrive/Colab Notebooks/DataCleansingCallCenter/Call-Center-Data-Messy.xlsx

# 4.Membaca Dataset

Membaca file Excel menggunakan pandas dan menyimpannya ke dalam DataFrame bernama df.

In [8]:
df = pd.read_excel(file_path)

print("Dataset berhasil dibaca.")
print("Ukuran dataset:", df.shape)

Dataset berhasil dibaca.
Ukuran dataset: (82, 12)

# 5.Menampilkan 5 Data Pertama

Digunakan untuk melihat struktur awal dan contoh isi dataset sebelum dilakukan cleansing.

In [9]:
df.head()

,ID,Customer Name,Sentiment,CSAT Score,Call Timestamp,Reason,City,State,Channel,Response Time,Call Duration (Minutes),Call Center
0,PAT-23706620,Rudie Tomsen,Positive,7.0,"January 20, 2024",payment,Johnstown,Pennsylvania,call-center,WITHIN SLA,9,Los Angeles/CA
1,VFG-63863025,Early Andrassy,Very Positive,9.0,08 Jan 2024,Billing question,Lansing,MI,chatbot,Within SLA,8,"los angeles, ca"
2,IJF-13083880,Garland Chuney,Negatif,3.0,2024-01-04 00:00:00,Billing Question,Little Rock,Arkansas,Call-Center,Within SLA,15,baltimore/md
3,mbn-58485152,Jude Traise,Very Positive,9.0,"January 28, 2024",Billing Question,Harrisburg,Pennsylvania,Web,Within sla,14,baltimore / md
4,okk-04567923,Zacherie Tigner,Very Negative,4.0,01/24/2024,Payments,Long Beach,CA,Call-Center,Within SLA,30,Baltimore/MD

# 6.Melihat 5 Data Terakhir

Memeriksa data pada bagian akhir dataset untuk memastikan file terbaca secara keseluruhan.

In [10]:
df.tail()

,ID,Customer Name,Sentiment,CSAT Score,Call Timestamp,Reason,City,State,Channel,Response Time,Call Duration (Minutes),Call Center
77,ZPZ-31710059,NaN,Very Positive,NaN,03-01-2024,payment,Pensacola,Florida,call-center,within SLA,9 min,Los Angeles/CA
78,TLA-11600824,Ganny Crampsy,Negative,3.0,2024/01/16,Service Outage,Minneapolis,Minnesota,Chatbot,within sla,35,"chicago, il"
79,xrx-56871498,Alric Scrane,NaN,4.0,20-01-2024,Payment,Washington,District of Columbia,Call-Center,Within SLA,30 min,Los Angeles/CA
80,kno-93249512,Maggi Simpson,Positive,9.0,2024/01/08,Payments,San Francisco,CA,Call-Center,Within SLA,9 min,Baltimore/MD
81,MHK-38443501,Tris Bent,Positive,8.0,01/02/2024,Billing Question,Tuscaloosa,Alabama,Website,within sla,26,Los Angeles / CA

# 7.Melihat Ukuran Dataset

Mengetahui jumlah baris dan jumlah kolom pada dataset.

In [11]:
print("Jumlah baris :", df.shape[0])
print("Jumlah kolom:", df.shape[1])

Jumlah baris : 82
Jumlah kolom: 12

# 8.Melihat Nama Kolom

Mengetahui seluruh atribut/variabel yang terdapat pada dataset.

In [12]:
print("Nama kolom:")
print(df.columns.tolist())

Nama kolom:
['ID', 'Customer Name', 'Sentiment', 'CSAT Score', 'Call Timestamp', 'Reason', 'City', 'State', 'Channel', 'Response Time', 'Call Duration (Minutes)', 'Call Center']

# 9.Melihat Informasi Dataset

info() digunakan untuk mengetahui tipe data setiap kolom dan jumlah data yang tersedia.

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82 entries, 0 to 81
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       82 non-null     object
 1   Customer Name            78 non-null     object
 2   Sentiment                81 non-null     object
 3   CSAT Score               79 non-null     float64
 4   Call Timestamp           82 non-null     object
 5   Reason                   82 non-null     object
 6   City                     80 non-null     object
 7   State                    80 non-null     object
 8   Channel                  78 non-null     object
 9   Response Time            81 non-null     object
 10  Call Duration (Minutes)  82 non-null     object
 11  Call Center              82 non-null     object
dtypes: float64(1), object(11)
memory usage: 7.8+ KB

# 10.Melihat Statistik Deskriptif

Digunakan untuk melihat statistik dasar, seperti jumlah data, rata-rata, nilai minimum, maksimum, dan kuartil.

In [14]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
ID,82,76,tcx-30032546,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer Name,78,71,Roobbie Pickervance,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sentiment,81,18,Negative,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CSAT Score,79.0,NaN,NaN,NaN,5.164557,2.388167,1.0,3.0,5.0,7.0,10.0
Call Timestamp,82,68,29-01-2024,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Reason,82,12,Billing Question,40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City,80,64,Chicago,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
State,80,40,California,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Channel,78,18,Call-Center,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Response Time,81,11,Within SLA,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Call Duration (Minutes),82.0,43.0,35.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Call Center,82,25,Baltimore/MD,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 11.Mengecek Missing Value

Missing value adalah data yang kosong atau tidak memiliki nilai. Pemeriksaan ini dilakukan sebelum menentukan metode penanganannya.

In [15]:
missing_data = df.isnull().sum()

print("Jumlah missing value setiap kolom:")
print(missing_data)

Jumlah missing value setiap kolom:
ID                         0
Customer Name              4
Sentiment                  1
CSAT Score                 3
Call Timestamp             0
Reason                     0
City                       2
State                      2
Channel                    4
Response Time              1
Call Duration (Minutes)    0
Call Center                0
dtype: int64

# 12.Menghitung Persentase Missing Value

Persentase missing value membantu mengetahui seberapa besar data kosong pada setiap kolom.

In [16]:
missing_percentage = (
    df.isnull().sum() / len(df) * 100
).sort_values(ascending=False)

print("Persentase missing value:")
print(missing_percentage)

Persentase missing value:
Customer Name              4.878049
Channel                    4.878049
CSAT Score                 3.658537
State                      2.439024
City                       2.439024
Sentiment                  1.219512
Response Time              1.219512
ID                         0.000000
Call Timestamp             0.000000
Reason                     0.000000
Call Duration (Minutes)    0.000000
Call Center                0.000000
dtype: float64

# 13.Mengecek Data Duplikat

Data duplikat adalah baris yang muncul lebih dari satu kali. Duplikasi dapat menyebabkan hasil analisis menjadi tidak akurat. Dan untuk melihat data yang duplikat menggunakan df.duplicated() dan menjumlahkan data yang duplikat menggunakan sum()

In [17]:
duplicate_count = df.duplicated().sum()

print("Jumlah data duplikat:", duplicate_count)

Jumlah data duplikat: 6

# 14.Mengecek Duplikasi Berdasarkan ID

Karena ID merupakan identitas setiap panggilan, pemeriksaan duplikasi berdasarkan ID penting untuk memastikan satu ID tidak tercatat berkali-kali.

In [18]:
duplicate_id = df['ID'].duplicated().sum()

print("Jumlah ID yang duplikat:", duplicate_id)

Jumlah ID yang duplikat: 6

# 15.Membuat Salinan Dataset

Dataset asli tidak langsung diubah. Membuat salinan bernama df_clean sebagai dataset hasil cleansing.

In [19]:
df_clean = df.copy()

print("DataFrame cleansing berhasil dibuat.")

DataFrame cleansing berhasil dibuat.

# 16.Membersihkan Spasi pada Data Teks

Menghapus spasi berlebih pada awal dan akhir teks, misalnya " Columbus " menjadi "Columbus".

In [20]:
object_columns = df_clean.select_dtypes(include='object').columns

for col in object_columns:
    df_clean[col] = (
        df_clean[col]
        .astype('string')
        .str.strip()
    )

print("Spasi berlebih berhasil dibersihkan.")

Spasi berlebih berhasil dibersihkan.

# 17.Membersihkan Kolom Customer Name

Menyeragamkan penulisan nama pelanggan agar lebih rapi.

In [21]:
df_clean['Customer Name'] = (
    df_clean['Customer Name']
    .astype('string')
    .str.strip()
    .str.title()
)

print(df_clean['Customer Name'].head())

0       Rudie Tomsen
1     Early Andrassy
2     Garland Chuney
3        Jude Traise
4    Zacherie Tigner
Name: Customer Name, dtype: string

# 18.Membersihkan Kolom Sentiment

Pada dataset terdapat beberapa bentuk penulisan sentiment seperti POSITIVE, positive, Positiv, Netral, VeryNegative, dan sebagainya. Semuanya dibuat menjadi kategori yang seragam.

In [22]:
sentiment_key = (
    df_clean['Sentiment']
    .astype('string')
    .str.lower()
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)

sentiment_map = {
    'positive': 'Positive',
    'positiv': 'Positive',
    'very positive': 'Very Positive',

    'negative': 'Negative',
    'negatif': 'Negative',
    'very negative': 'Very Negative',
    'verynegative': 'Very Negative',

    'neutral': 'Neutral',
    'netral': 'Neutral'
}

df_clean['Sentiment'] = sentiment_key.map(sentiment_map)

print(df_clean['Sentiment'].value_counts(dropna=False))

Sentiment
Negative         33
Very Negative    17
Neutral          12
Positive         11
Very Positive     8
NaN               1
Name: count, dtype: int64

# 19.Membersihkan Kolom Reason

Menyamakan variasi penulisan kategori alasan pelanggan.

In [23]:
reason_key = (
    df_clean['Reason']
    .astype('string')
    .str.lower()
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)

reason_map = {
    'billing question': 'Billing Question',
    'billing questions': 'Billing Question',
    'payment': 'Payment',
    'payments': 'Payment',
    'service outage': 'Service Outage'
}

df_clean['Reason'] = reason_key.map(reason_map)

print(df_clean['Reason'].value_counts(dropna=False))

Reason
Billing Question    59
Payment             13
Service Outage      10
Name: count, dtype: int64

# 20.Membersihkan Kolom City

Membersihkan spasi, menyeragamkan huruf, serta mengubah singkatan kota tertentu menjadi nama yang lebih konsisten.

In [24]:
city_key = (
    df_clean['City']
    .astype('string')
    .str.strip()
    .str.lower()
)

city_map = {
    'ft. wayne': 'Fort Wayne',
    'ft. pierce': 'Fort Pierce',
    'ft. worth': 'Fort Worth'
}

df_clean['City'] = (
    city_key
    .map(city_map)
    .fillna(city_key.str.title())
)

print(df_clean['City'].value_counts(dropna=False))

City
Fort Pierce         4
Washington          3
Salt Lake City      3
New York City       3
Chicago             3
Columbus            3
Stockton            2
<NA>                2
Little Rock         2
Montgomery          2
Santa Ana           2
Pasadena            2
Lubbock             2
Charleston          2
Fort Myers          2
Shawnee Mission     2
Minneapolis         2
Abilene             2
Kansas City         1
Fort Wayne          1
Evansville          1
Lansing             1
Harrisburg          1
Johnstown           1
Long Beach          1
Huntington          1
Bronx               1
Houston             1
Corpus Christi      1
Providence          1
Naperville          1
Gainesville         1
St Paul             1
Nashville           1
Bloomington         1
Tucson              1
Dallas              1
Des Moines          1
Madison             1
El Paso             1
Baton Rouge         1
Richmond            1
Las Vegas           1
Pittsburgh          1
Rockford            1
Sacramento          1
Reno                1
Colorado Springs    1
Erie                1
Honolulu            1
Concord             1
Fort Lauderdale     1
South Lake Tahoe    1
Fort Worth          1
Pensacola           1
San Francisco       1
Tuscaloosa          1
Name: count, dtype: int64

# 21.Membersihkan Kolom State

Kolom State memiliki campuran antara singkatan seperti CA, TX, MI dan nama lengkap. Semuanya diubah menjadi nama lengkap.

In [25]:
state_key = (
    df_clean['State']
    .astype('string')
    .str.strip()
    .str.lower()
)

state_map = {
    'al': 'Alabama',
    'ar': 'Arkansas',
    'az': 'Arizona',
    'ca': 'California',
    'co': 'Colorado',
    'dc': 'District of Columbia',
    'fl': 'Florida',
    'ga': 'Georgia',
    'hi': 'Hawaii',
    'ia': 'Iowa',
    'il': 'Illinois',
    'in': 'Indiana',
    'ks': 'Kansas',
    'la': 'Louisiana',
    'mi': 'Michigan',
    'mn': 'Minnesota',
    'mo': 'Missouri',
    'nv': 'Nevada',
    'ny': 'New York',
    'oh': 'Ohio',
    'pa': 'Pennsylvania',
    'ri': 'Rhode Island',
    'sc': 'South Carolina',
    'tn': 'Tennessee',
    'tx': 'Texas',
    'ut': 'Utah',
    'va': 'Virginia',
    'wi': 'Wisconsin',
    'wv': 'West Virginia'
}

df_clean['State'] = (
    state_key
    .map(state_map)
    .fillna(state_key.str.title())
)

print(df_clean['State'].value_counts(dropna=False))

State
California              10
Texas                   10
Florida                  8
Illinois                 6
Minnesota                4
New York                 4
Pennsylvania             4
Alabama                  3
Utah                     3
Kansas                   2
District of Columbia     2
West Virginia            2
<NA>                     2
Arkansas                 2
Indiana                  2
Georgia                  2
Nevada                   2
Michigan                 1
Missouri                 1
Rhode Island             1
Tennessee                1
Louisiana                1
South Carolina           1
Iowa                     1
Wisconsin                1
Arizona                  1
Ohio                     1
Virginia                 1
Colorado                 1
Hawaii                   1
District Of Columbia     1
Name: count, dtype: int64

# 22.Membersihkan Kolom Channel

Menyamakan beberapa bentuk penulisan seperti Call-Center, CALL CENTER, Chat Bot, Chat-bot, E-mail, dan Website.

In [26]:
channel_key = (
    df_clean['Channel']
    .astype('string')
    .str.lower()
    .str.replace(r'[\s-]+', ' ', regex=True)
    .str.strip()
)

channel_map = {
    'call center': 'Call Center',
    'chatbot': 'Chatbot',
    'chat bot': 'Chatbot',
    'email': 'Email',
    'e mail': 'Email',
    'web': 'Web',
    'website': 'Web'
}

df_clean['Channel'] = channel_key.map(channel_map)

print(df_clean['Channel'].value_counts(dropna=False))

Channel
Chatbot        26
Call Center    25
Web            19
Email           8
NaN             4
Name: count, dtype: int64

# 23.Membersihkan Kolom Response Time

Menyamakan penulisan Within sla, WITHIN SLA, dan bentuk lainnya menjadi format yang sama.

In [27]:
response_key = (
    df_clean['Response Time']
    .astype('string')
    .str.lower()
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)

response_map = {
    'within sla': 'Within SLA',
    'above sla': 'Above SLA',
    'below sla': 'Below SLA'
}

df_clean['Response Time'] = response_key.map(response_map)

print(df_clean['Response Time'].value_counts(dropna=False))

Response Time
Within SLA    59
Above SLA     11
Below SLA     11
NaN            1
Name: count, dtype: int64

# 24.Membersihkan Kolom Call Center

Menyamakan format penulisan lokasi call center seperti Los Angeles / CA, Los Angeles, CA, Los Angeles-CA, dan Los Angeles/CA.

In [28]:
call_center_key = (
    df_clean['Call Center']
    .astype('string')
    .str.lower()
    .str.replace(r'\s*[/,-]\s*', '/', regex=True)
    .str.strip()
)

call_center_map = {
    'los angeles/ca': 'Los Angeles/CA',
    'baltimore/md': 'Baltimore/MD',
    'chicago/il': 'Chicago/IL',
    'denver/co': 'Denver/CO'
}

df_clean['Call Center'] = call_center_key.map(call_center_map)

print(df_clean['Call Center'].value_counts(dropna=False))

Call Center
Los Angeles/CA    34
Baltimore/MD      33
Chicago/IL         8
Denver/CO          7
Name: count, dtype: int64

# 25.Membersihkan CSAT Score

CSAT Score harus berupa angka. Pada tahap ini data diubah menjadi tipe numerik dan nilai di luar rentang 1–10 dianggap tidak valid.

In [29]:
df_clean['CSAT Score'] = pd.to_numeric(
    df_clean['CSAT Score'],
    errors='coerce'
)

df_clean.loc[
    ~df_clean['CSAT Score'].between(1, 10),
    'CSAT Score'
] = np.nan

print(df_clean['CSAT Score'].describe())

count    79.000000
mean      5.164557
std       2.388167
min       1.000000
25%       3.000000
50%       5.000000
75%       7.000000
max      10.000000
Name: CSAT Score, dtype: float64

# 26.Membersihkan Call Duration

Durasi panggilan masih memiliki variasi seperti 23, 23 min, 25 min, dan sebagainya. Angka diekstrak sehingga seluruh data menjadi numerik.

In [30]:
df_clean['Call Duration (Minutes)'] = (
    df_clean['Call Duration (Minutes)']
    .astype('string')
    .str.extract(r'(\d+(?:\.\d+)?)', expand=False)
)

df_clean['Call Duration (Minutes)'] = pd.to_numeric(
    df_clean['Call Duration (Minutes)'],
    errors='coerce'
)

print(df_clean['Call Duration (Minutes)'].head(10))

0     9
1     8
2    15
3    14
4    30
5    42
6    23
7     7
8    22
9    20
Name: Call Duration (Minutes), dtype: Int64

# 27.Membersihkan Format Call Timestamp

Tanggal pada dataset memiliki beberapa format berbeda, misalnya January 20, 2024, 08 Jan 2024, 2024-01-04, 01/24/2024, dan 29-01-2024. Semua diubah menjadi format datetime.

In [31]:
df_clean['Call Timestamp'] = pd.to_datetime(
    df_clean['Call Timestamp'],
    errors='coerce',
    format='mixed'
)

print(df_clean['Call Timestamp'].head(10))
print("\nTipe data:", df_clean['Call Timestamp'].dtype)

0   2024-01-20
1   2024-01-08
2   2024-01-04
3   2024-01-28
4   2024-01-24
5   2024-01-24
6   2024-01-27
7   2024-01-24
8   2024-01-24
9   2024-01-08
Name: Call Timestamp, dtype: datetime64[ns]

Tipe data: datetime64[ns]

# 28.Mengecek Tanggal yang Gagal Dikonversi

Memastikan tidak ada tanggal yang gagal diproses menjadi format datetime.

In [32]:
invalid_date = df_clean['Call Timestamp'].isna().sum()

print("Jumlah tanggal yang gagal dikonversi:", invalid_date)

Jumlah tanggal yang gagal dikonversi: 0

# 29.Menghapus Data Duplikat Berdasarkan ID

Karena ID merupakan identitas unik setiap data panggilan, data dengan ID yang sama dipertahankan satu saja.

In [33]:
df_clean = (
    df_clean
    .drop_duplicates(subset='ID', keep='first')
    .reset_index(drop=True)
)

print("Jumlah data setelah menghapus duplikat:", len(df_clean))
print("Jumlah ID duplikat:", df_clean['ID'].duplicated().sum())

Jumlah data setelah menghapus duplikat: 73
Jumlah ID duplikat: 0

# 30.Menangani Missing Value

Missing value ditangani berdasarkan tipe data. Data kategori diberi label Unknown, sedangkan data numerik menggunakan median.

In [34]:
categorical_columns = [
    'Customer Name',
    'Sentiment',
    'City',
    'State',
    'Channel',
    'Response Time'
]

for col in categorical_columns:
    df_clean[col] = df_clean[col].fillna('Unknown')

df_clean['CSAT Score'] = df_clean['CSAT Score'].fillna(
    df_clean['CSAT Score'].median()
)

df_clean['Call Duration (Minutes)'] = (
    df_clean['Call Duration (Minutes)']
    .fillna(
        df_clean['Call Duration (Minutes)'].median()
    )
)

print("Missing value telah ditangani.")

Missing value telah ditangani.

# 31.Mengubah Tipe Data Numerik

Memastikan CSAT dan durasi panggilan mempunyai tipe data numerik yang sesuai.

In [35]:
df_clean['CSAT Score'] = df_clean['CSAT Score'].astype('Int64')

df_clean['Call Duration (Minutes)'] = (
    df_clean['Call Duration (Minutes)']
    .astype('Int64')
)

print(df_clean.dtypes)

ID                         string[python]
Customer Name              string[python]
Sentiment                          object
CSAT Score                          Int64
Call Timestamp             datetime64[ns]
Reason                             object
City                               object
State                              object
Channel                            object
Response Time                      object
Call Duration (Minutes)             Int64
Call Center                        object
dtype: object

# 32.Pemeriksaan Outlier Call Duration

IQR digunakan untuk mendeteksi nilai durasi panggilan yang jauh dari distribusi data. Pada tahap ini data belum langsung dihapus.

In [36]:
Q1 = df_clean['Call Duration (Minutes)'].quantile(0.25)
Q3 = df_clean['Call Duration (Minutes)'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - (1.5 * IQR)
upper_bound = Q3 + (1.5 * IQR)

outlier_duration = df_clean[
    (df_clean['Call Duration (Minutes)'] < lower_bound) |
    (df_clean['Call Duration (Minutes)'] > upper_bound)
]

print("Q1            :", Q1)
print("Q3            :", Q3)
print("IQR           :", IQR)
print("Batas bawah   :", lower_bound)
print("Batas atas    :", upper_bound)
print("Jumlah outlier:", len(outlier_duration))

Q1            : 14.0
Q3            : 36.0
IQR           : 22.0
Batas bawah   : -19.0
Batas atas    : 69.0
Jumlah outlier: 0

# 33.Melihat Data Outlier

Menampilkan data yang terdeteksi sebagai outlier untuk pemeriksaan sebelum diputuskan apakah perlu dihapus atau tidak.

In [37]:
outlier_duration[
    [
        'ID',
        'Customer Name',
        'Call Duration (Minutes)',
        'Call Timestamp',
        'Call Center'
    ]
]

Empty DataFrame
Columns: [ID, Customer Name, Call Duration (Minutes), Call Timestamp, Call Center]
Index: []

# 34.Pemeriksaan Missing Value Setelah Cleansing

Digunakan untuk memastikan nilai kosong yang penting sudah berhasil ditangani.

In [38]:
print("Missing value setelah cleansing:")
print(df_clean.isnull().sum())

Missing value setelah cleansing:
ID                         0
Customer Name              0
Sentiment                  0
CSAT Score                 0
Call Timestamp             0
Reason                     0
City                       0
State                      0
Channel                    0
Response Time              0
Call Duration (Minutes)    0
Call Center                0
dtype: int64

# 35.Pemeriksaan Duplikasi Setelah Cleansing

Memastikan ID sudah tidak memiliki duplikasi.

In [39]:
print("Duplikasi seluruh baris:", df_clean.duplicated().sum())
print("Duplikasi berdasarkan ID:", df_clean['ID'].duplicated().sum())

Duplikasi seluruh baris: 0
Duplikasi berdasarkan ID: 0

# 36.Menampilkan Struktur Data Setelah Cleansing

Melihat tipe data dan jumlah data setelah seluruh proses cleansing selesai.

In [40]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73 entries, 0 to 72
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       73 non-null     string
 1   Customer Name            73 non-null     string
 2   Sentiment                73 non-null     object
 3   CSAT Score               73 non-null     Int64
 4   Call Timestamp           73 non-null     datetime64[ns]
 5   Reason                   73 non-null     object
 6   City                     73 non-null     object
 7   State                    73 non-null     object
 8   Channel                  73 non-null     object
 9   Response Time            73 non-null     object
 10  Call Duration (Minutes)  73 non-null     Int64
 11  Call Center              73 non-null     object
dtypes: Int64(2), datetime64[ns](1), object(7), string(2)
memory usage: 7.1+ KB

# 37.Menampilkan Hasil Akhir

Menampilkan data hasil cleansing untuk pengecekan terakhir.

In [41]:
df_clean.head(10)

,ID,Customer Name,Sentiment,CSAT Score,Call Timestamp,Reason,City,State,Channel,Response Time,Call Duration (Minutes),Call Center
0,PAT-23706620,Rudie Tomsen,Positive,7,2024-01-20,Payment,Johnstown,Pennsylvania,Call Center,Within SLA,9,Los Angeles/CA
1,VFG-63863025,Early Andrassy,Very Positive,9,2024-01-08,Billing Question,Lansing,Michigan,Chatbot,Within SLA,8,Los Angeles/CA
2,IJF-13083880,Garland Chuney,Negative,3,2024-01-04,Billing Question,Little Rock,Arkansas,Call Center,Within SLA,15,Baltimore/MD
3,mbn-58485152,Jude Traise,Very Positive,9,2024-01-28,Billing Question,Harrisburg,Pennsylvania,Web,Within SLA,14,Baltimore/MD
4,okk-04567923,Zacherie Tigner,Very Negative,4,2024-01-24,Payment,Long Beach,California,Call Center,Within SLA,30,Baltimore/MD
5,TPZ-92635583,Eartha Boner,Positive,8,2024-01-24,Service Outage,Fort Wayne,Indiana,Chatbot,Within SLA,42,Los Angeles/CA
6,WMA-45712668,Angie Francklin,Negative,4,2024-01-27,Billing Question,Evansville,Indiana,Email,Within SLA,23,Los Angeles/CA
7,JOT-87331404,Loralee Shivell,Neutral,8,2024-01-24,Service Outage,Kansas City,Missouri,Chatbot,Within SLA,7,Baltimore/MD
8,tcx-30032546,Madelena Pinnock,Negative,4,2024-01-24,Service Outage,Fort Pierce,Florida,Chatbot,Above SLA,22,Baltimore/MD
9,YLF-83918836,Bogey Mcreath,Positive,7,2024-01-08,Billing Question,New York City,New York,Web,Within SLA,20,Baltimore/MD

# 38.Melihat Seluruh Dataset Hasil Cleansing

Digunakan untuk melakukan pemeriksaan manual terhadap seluruh data yang telah dibersihkan.

In [42]:
pd.set_option('display.max_columns', None)

df_clean

,ID,Customer Name,Sentiment,CSAT Score,Call Timestamp,Reason,City,State,Channel,Response Time,Call Duration (Minutes),Call Center
0,PAT-23706620,Rudie Tomsen,Positive,7,2024-01-20,Payment,Johnstown,Pennsylvania,Call Center,Within SLA,9,Los Angeles/CA
1,VFG-63863025,Early Andrassy,Very Positive,9,2024-01-08,Billing Question,Lansing,Michigan,Chatbot,Within SLA,8,Los Angeles/CA
2,IJF-13083880,Garland Chuney,Negative,3,2024-01-04,Billing Question,Little Rock,Arkansas,Call Center,Within SLA,15,Baltimore/MD
3,mbn-58485152,Jude Traise,Very Positive,9,2024-01-28,Billing Question,Harrisburg,Pennsylvania,Web,Within SLA,14,Baltimore/MD
4,okk-04567923,Zacherie Tigner,Very Negative,4,2024-01-24,Payment,Long Beach,California,Call Center,Within SLA,30,Baltimore/MD
...,...,...,...,...,...,...,...,...,...,...,...,...
68,ZPZ-31710059,Unknown,Very Positive,5,2024-03-01,Payment,Pensacola,Florida,Call Center,Within SLA,9,Los Angeles/CA
69,TLA-11600824,Ganny Crampsy,Negative,3,2024-01-16,Service Outage,Minneapolis,Minnesota,Chatbot,Within SLA,35,Chicago/IL
70,xrx-56871498,Alric Scrane,Unknown,4,2024-01-20,Payment,Washington,District Of Columbia,Call Center,Within SLA,30,Los Angeles/CA
71,kno-93249512,Maggi Simpson,Positive,9,2024-01-08,Payment,San Francisco,California,Call Center,Within SLA,9,Baltimore/MD
72,MHK-38443501,Tris Bent,Positive,8,2024-01-02,Billing Question,Tuscaloosa,Alabama,Web,Within SLA,26,Los Angeles/CA

# 39.Statistik Dataset Setelah Cleansing

Melihat kembali statistik dataset setelah data dibersihkan.

In [43]:
df_clean.describe(include='all').T

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
ID,73,73,PAT-23706620,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer Name,73,67,Unknown,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sentiment,73,6,Negative,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CSAT Score,73.0,<NA>,<NA>,<NA>,5.123288,1.0,3.0,5.0,7.0,10.0,2.338953
Call Timestamp,73,NaN,NaN,NaN,2024-02-01 23:40:16.438356224,2024-01-01 00:00:00,2024-01-11 00:00:00,2024-01-20 00:00:00,2024-01-27 00:00:00,2024-11-01 00:00:00,NaN
Reason,73,3,Billing Question,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City,73,57,Fort Pierce,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
State,73,31,California,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Channel,73,5,Chatbot,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Response Time,73,4,Within SLA,54,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Call Duration (Minutes),73.0,<NA>,<NA>,<NA>,26.671233,6.0,14.0,30.0,36.0,45.0,12.482271
Call Center,73,4,Los Angeles/CA,32,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 40.Menyimpan Dataset Hasil Cleansing

Menyimpan dataset yang sudah dibersihkan ke dalam file Excel baru sehingga file asli tidak berubah.

In [46]:
output_path = '/content/drive/MyDrive/Colab Notebooks/DataCleansingCallCenter/Call-Center-Data-Cleaned.xlsx'

df_clean.to_excel(
    output_path,
    index=False
)

print("Data berhasil disimpan.")
print(output_path)

Data berhasil disimpan.
/content/drive/MyDrive/Colab Notebooks/DataCleansingCallCenter/Call-Center-Data-Cleaned.xlsx

# 41.Verifikasi File Hasil Cleansing

Membaca kembali file hasil cleansing untuk memastikan proses penyimpanan berhasil.

In [47]:
df_check = pd.read_excel(output_path)

print("File hasil cleansing berhasil dibaca kembali.")
print("Ukuran data:", df_check.shape)

df_check.head()

File hasil cleansing berhasil dibaca kembali.
Ukuran data: (73, 12)

,ID,Customer Name,Sentiment,CSAT Score,Call Timestamp,Reason,City,State,Channel,Response Time,Call Duration (Minutes),Call Center
0,PAT-23706620,Rudie Tomsen,Positive,7,2024-01-20,Payment,Johnstown,Pennsylvania,Call Center,Within SLA,9,Los Angeles/CA
1,VFG-63863025,Early Andrassy,Very Positive,9,2024-01-08,Billing Question,Lansing,Michigan,Chatbot,Within SLA,8,Los Angeles/CA
2,IJF-13083880,Garland Chuney,Negative,3,2024-01-04,Billing Question,Little Rock,Arkansas,Call Center,Within SLA,15,Baltimore/MD
3,mbn-58485152,Jude Traise,Very Positive,9,2024-01-28,Billing Question,Harrisburg,Pennsylvania,Web,Within SLA,14,Baltimore/MD
4,okk-04567923,Zacherie Tigner,Very Negative,4,2024-01-24,Payment,Long Beach,California,Call Center,Within SLA,30,Baltimore/MD